[package]
name = "pengj-templates-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "pengj-templates 命令行工具"

[[bin]]
name = "pengj-templates-cli"
path = "src/main.rs"

[dependencies]
pengj-core = { path = "../core" }
clap.workspace = true
anyhow.workspace = true
serde_json.workspace = true
